### ISSUE TITLE
Login screen doesn't tell you what server you're logging into

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#275]
<img width="506" alt="Screenshot 2022-09-19 at 22 48 43" src="https://user-images.githubusercontent.com/1294269/191125795-306759e9-0262-4f15-8a19-2e98068f0050.png">

Is this trying to log me into the thirdroom.io server or the thirdroom.dev server or somewhere else?

**Comment by hughns** [comment]
The wording has now been updated so that it looks like this:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/6955675/191222833-7a15406d-1034-4fc1-b241-889caa0980e4.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/6955675/191223145-163c6b4b-9db7-4369-aee9-6e59dc97e3dc.png">

...which hopefully makes it clearer.

@ajbura the "* Required fields" now looks a bit funny... could you take a look at the CSS?

**Comment by ara4n** [comment]
thanks!

**Comment by ajbura** [comment]
@hughns Could the register page captcha be compact (like what we have during guest access)?

**Comment by hughns** [comment]
@ajbura yes, i've had to import the whole `.ftl` templates for registration but this is now done.

Latest looks like this:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/6955675/191257476-2f0e7c9b-0239-4b39-9645-5218a3dbe9b7.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/6955675/191257523-cc6eeca1-4bde-4eb8-8304-ed84b75b8359.png">

**Comment by ajbura** [comment]
thanks!

**Comment by ajbura** [comment]
@hughns https://github.com/matrix-org/thirdroom-keycloak-theme/pull/4

**Comment by hughns** [comment]
It now looks like this:

![image](https://user-images.githubusercontent.com/6955675/191570764-942e0f80-e591-4666-a867-51bb07e25197.png)
